services:
  - type: web
    name: Mantra-MD
    env: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: SESSION_ID
        sync: false
      - key: NODE_VERSION
        value: 20.x